
name: Build & Deploy to FTP

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"   # Every day at 11:00 UTC
  workflow_dispatch:        # Optional: run manually from the Actions tab

concurrency:
  group: deploy-to-ftp
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build site and deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main  # Ensures scheduled runs build from main

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          CI: true
        run: npm run build

      # Optional: verify the build artifact exists (helps fail fast with a clear error)
      - name: Verify build output exists
        run: |
          test -d dist && echo "dist/ found" || (echo "dist/ not found. Check your build." && exit 1)

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /public_html/
          dangerous-clean-slate: false
